version: '3.8'

name: "formationOpenclassrooms"

services:
  svc_mysql:
    container_name: 'foc_db_mysql'
    restart: always
    #image: mysql:8.0.32
    build: ./docker/mysql
    volumes:
      - foc_db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - foc_vlan

  svc_php_fpm:
    container_name: 'foc_php_fpm'
    restart: 'always'
    build: ./docker/php
    depends_on:
      - svc_mysql
    links:
      - 'svc_mysql'
    working_dir: /var/www
    volumes:
      - ./project:/var/www
    networks:
      - foc_vlan

  svc_nginx:
    container_name: 'foc_nginx'
    restart: 'always'
    build: ./docker/nginx
    depends_on:
      - svc_php_fpm
    links:
      - 'svc_php_fpm'
    working_dir: /var/www
    volumes:
      - ./project:/var/www
    networks:
      - foc_vlan
    ports:
      - "8003:80"

  svc_pma:
    container_name: 'foc_pma'
    restart: always
    image: phpmyadmin:latest
    depends_on:
      - svc_mysql
    ports:
      - "8083:80"
    environment:
      PMA_HOST: svc_mysql
    networks:
      - foc_vlan

volumes:
  foc_db_data:

networks:
  foc_vlan:
    name: foc_vlan
    external: false
